name: Docker

on:
    workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{secrets.USER_DOCKERHUB}}
        password: ${{secrets.PASSWORD_DOCKERHUB}}

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: kassiocarvalho/go_ci:${{github.ref_name}}